name: c static analysis
on: [ push, pull_request ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: see dirs and files
        run: ls -la
        
      - name: install cppcheck
        run: sudo apt-get install cppcheck
        
      - name: run cpp check
        run: cppcheck ./src
